version: '3.1'

services:
  zoo:
    image: zookeeper
    restart: always
    hostname: zoo
    ports:
      - 2181:2181

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: purepurr
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:9090

  hadoop:
    image: uhopper/hadoop-namenode
    hostname: hadoop
    domainname: hadoop
    container_name: hadoop
    environment:
      - CLUSTER_NAME=dev
    ports:
      - 50070:50070
